user www-data;
worker_processes auto;
worker_cpu_affinity auto;
pid /run/nginx.pid;
error_log /var/log/nginx/error.log;
include /etc/nginx/modules-enabled/*.conf;

events {
    worker_connections 512;

}

http {

server {
    listen 80;
    server_name example.com;
    
    # gzip
    gzip on;
    # log
    access_log /var/log/nginx/access.log;

    location /static/ {
        alias /home/pi/blog-test/static/;
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    location /data/users/avatars/ {
        alias /home/pi/blog-test/data/users/avatars/;
        expires 30d;
    }

    location / {
        # include proxy_params;
        proxy_pass http://unix:/var/www/blog-test/myapp.sock; #http://unix:/home/pi/blog-test/myapp.sock;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

    }
    location /data/ {
        deny all;
        return 403;
    }
    location /protected/ {
        internal;
        alias /home/pi/blog-test/private/;
    }
}

}