
server {
    listen 80;
    server_name example.com;

    location /ststic/ {
        alias /home/pi/blog-test/static;
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    location /data/users/avatars/ {
        alias /home/pi/blog-test/data/users/avatars/;
        expires 30d;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/home/pi/blog-test/myapp.sock;

    }
    location /data/ {
        deny all;
        return 403;
    }
    location /protected/ {
        internal;
        alias /home/pi/blog-test/private/;
    }
}